-- Backfill sessions_hourly_mv with last 90 days of data
-- This will pre-aggregate historical session data for faster analytics queries

INSERT INTO sessions_hourly_mv
SELECT
    workspace_id,
    project_id,
    campaign_id,
    environment,
    campaign_environment,
    toStartOfHour(timestamp) AS hour,
    sumState(CAST(1 AS UInt64)) AS session_count,
    uniqState(session_id) AS unique_sessions,
    uniqState(user_id) AS unique_users,
    sumState(CAST(if(is_returning = 0, 1, 0) AS UInt64)) AS new_sessions,
    sumState(CAST(if(is_returning = 1, 1, 0) AS UInt64)) AS returning_sessions,
    sumState(CAST(coalesce(session_duration, 0) AS Float64)) AS total_duration,
    sumState(CAST(if(session_duration < 3, 1, 0) AS UInt64)) AS bounced_sessions,
    coalesce(nullIf(device_type, ''), 'Unknown') AS device_type,
    coalesce(nullIf(device_os, ''), 'Unknown') AS device_os,
    coalesce(nullIf(browser, ''), 'Unknown') AS browser,
    is_mobile,
    coalesce(nullIf(country, ''), 'Unknown') AS country,
    coalesce(nullIf(city, ''), 'Unknown') AS city,
    coalesce(nullIf(region, ''), 'Unknown') AS region,
    coalesce(nullIf(continent, ''), 'Unknown') AS continent,
    coalesce(nullIf(language, ''), 'Unknown') AS language,
    coalesce(nullIf(timezone, ''), 'Unknown') AS timezone,
    coalesce(nullIf(utm_source, ''), 'Direct') AS utm_source,
    coalesce(nullIf(utm_medium, ''), 'Direct') AS utm_medium,
    coalesce(nullIf(utm_campaign, ''), 'Direct') AS utm_campaign,
    coalesce(nullIf(referrer, ''), 'Direct') AS referrer,
    coalesce(nullIf(source, ''), 'Direct') AS source,
    coalesce(nullIf(ref, ''), 'Direct') AS ref,
    coalesce(nullIf(landing_page_id, ''), 'Unknown') AS landing_page_id,
    coalesce(nullIf(segment_id, ''), 'Unknown') AS segment_id,
    coalesce(nullIf(ab_test_variant_id, ''), 'Unknown') AS ab_test_variant_id,
    toHour(timestamp) AS hour_of_day,
    toDayOfWeek(timestamp) AS day_of_week
FROM session_v1
WHERE timestamp >= now() - INTERVAL 90 DAY
  AND timestamp < now()
GROUP BY
    workspace_id,
    project_id,
    campaign_id,
    environment,
    campaign_environment,
    hour,
    device_type,
    device_os,
    browser,
    is_mobile,
    country,
    city,
    region,
    continent,
    language,
    timezone,
    utm_source,
    utm_medium,
    utm_campaign,
    referrer,
    source,
    ref,
    landing_page_id,
    segment_id,
    ab_test_variant_id,
    hour_of_day,
    day_of_week
