// Font data with grouping
export const SANS_FONTS = {
  google: [
    { value: "Inter", label: "Inter" },
    { value: "Roboto", label: "Roboto" },
    { value: "Open Sans", label: "Open Sans" },
    { value: "Lato", label: "Lato" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Nunito", label: "Nunito" },
    { value: "Poppins", label: "Poppins" },
    { value: "Source Sans Pro", label: "Source Sans Pro" },
    { value: "Work Sans", label: "Work Sans" },
    { value: "Fira Sans", label: "Fira Sans" },
    { value: "DM Sans", label: "DM Sans" },
    { value: "Plus Jakarta Sans", label: "Plus Jakarta Sans" },
    { value: "Manrope", label: "Manrope" },
    { value: "Outfit", label: "Outfit" },
    { value: "Space Grotesk", label: "Space Grotesk" },
    { value: "Lexend", label: "Lexend" },
    { value: "Public Sans", label: "Public Sans" },
    { value: "Karla", label: "Karla" },
    { value: "Quicksand", label: "Quicksand" },
    { value: "Oxygen", label: "Oxygen" },
    { value: "IBM Plex Sans", label: "IBM Plex Sans" },
    { value: "Raleway", label: "Raleway" },
    { value: "Rubik", label: "Rubik" },
    { value: "Mukti", label: "Mukti" },
  ],
  system: [
    { value: "Arial", label: "Arial" },
    { value: "Helvetica", label: "Helvetica" },
    { value: "Helvetica Neue", label: "Helvetica Neue" },
    { value: "Segoe UI", label: "Segoe UI" },
    { value: "San Francisco", label: "San Francisco" },
    { value: "system-ui", label: "System UI" },
    { value: "sans-serif", label: "Sans Serif" },
  ],
};

export const SERIF_FONTS = {
  google: [
    { value: "Playfair Display", label: "Playfair Display" },
    { value: "Lora", label: "Lora" },
    { value: "Merriweather", label: "Merriweather" },
    { value: "Crimson Text", label: "Crimson Text" },
    { value: "PT Serif", label: "PT Serif" },
    { value: "Source Serif Pro", label: "Source Serif Pro" },
    { value: "Libre Baskerville", label: "Libre Baskerville" },
    { value: "EB Garamond", label: "EB Garamond" },
    { value: "Cormorant Garamond", label: "Cormorant Garamond" },
    { value: "Vollkorn", label: "Vollkorn" },
    { value: "Spectral", label: "Spectral" },
    { value: "Bitter", label: "Bitter" },
    { value: "Alegreya", label: "Alegreya" },
    { value: "Domine", label: "Domine" },
    { value: "Neuton", label: "Neuton" },
    { value: "Cardo", label: "Cardo" },
    { value: "Old Standard TT", label: "Old Standard TT" },
    { value: "Libre Caslon Text", label: "Libre Caslon Text" },
    { value: "Arvo", label: "Arvo" },
    { value: "Roboto Slab", label: "Roboto Slab" },
    { value: "IBM Plex Serif", label: "IBM Plex Serif" },
    { value: "Literata", label: "Literata" },
    { value: "Noticia Text", label: "Noticia Text" },
    { value: "Gelasio", label: "Gelasio" },
    { value: "Zilla Slab", label: "Zilla Slab" },
  ],
  system: [
    { value: "Times New Roman", label: "Times New Roman" },
    { value: "Georgia", label: "Georgia" },
    { value: "Times", label: "Times" },
    { value: "serif", label: "Serif" },
  ],
};

export const MONO_FONTS = {
  google: [
    { value: "JetBrains Mono", label: "JetBrains Mono" },
    { value: "Fira Code", label: "Fira Code" },
    { value: "Source Code Pro", label: "Source Code Pro" },
    { value: "Roboto Mono", label: "Roboto Mono" },
    { value: "Space Mono", label: "Space Mono" },
    { value: "IBM Plex Mono", label: "IBM Plex Mono" },
    { value: "Inconsolata", label: "Inconsolata" },
    { value: "Ubuntu Mono", label: "Ubuntu Mono" },
    { value: "Fira Mono", label: "Fira Mono" },
    { value: "PT Mono", label: "PT Mono" },
    { value: "Anonymous Pro", label: "Anonymous Pro" },
    { value: "Cousine", label: "Cousine" },
    { value: "Share Tech Mono", label: "Share Tech Mono" },
    { value: "Overpass Mono", label: "Overpass Mono" },
    { value: "Azeret Mono", label: "Azeret Mono" },
    { value: "B612 Mono", label: "B612 Mono" },
    { value: "DM Mono", label: "DM Mono" },
    { value: "Red Hat Mono", label: "Red Hat Mono" },
    { value: "VT323", label: "VT323" },
    { value: "Major Mono Display", label: "Major Mono Display" },
    { value: "Nova Mono", label: "Nova Mono" },
    { value: "Cutive Mono", label: "Cutive Mono" },
    { value: "Oxygen Mono", label: "Oxygen Mono" },
  ],
  system: [
    { value: "Monaco", label: "Monaco" },
    { value: "Consolas", label: "Consolas" },
    { value: "SF Mono", label: "SF Mono" },
    { value: "Menlo", label: "Menlo" },
    { value: "Courier New", label: "Courier New" },
    { value: "Courier", label: "Courier" },
    { value: "monospace", label: "Monospace" },
  ],
};

// Radius options with visual representations
export const RADIUS_OPTIONS = [
  {
    value: "0",
    label: "None",
    description: "No rounded corners.",
  },
  {
    value: "0.5rem",
    label: "Small",
    description: "Subtle roundness (0.5rem)",
  },
  {
    value: "1rem",
    label: "Medium",
    description: "Moderate roundness (1rem)",
  },
  {
    value: "1.5rem",
    label: "Large",
    description: "High roundness (1.5rem)",
  },
];

// Define the order of color categories
export const COLOR_CATEGORY_ORDER = [
  "primary",
  "secondary",
  "accent",
  "base",
  "card",
  "muted",
  "destructive",
  "border",
];
